language: python
sudo: false
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
install:
    - pip install tox
script:
    - tox
notifications:
    email: false
